backend:
  name: github
  repo: yuanjimaster/acupuncture-site
  branch: main

media_folder: "assets" # 以后上传的照片都会存到这里
public_folder: "assets"

collections:
  - name: "pages"
    label: "网页内容管理"
    files:
      - file: "index.html"
        label: "首页修改"
        name: "home"
        fields:
          - {label: "页面标题", name: "title", widget: "string"}
          - {label: "主内容区", name: "body", widget: "markdown"}
